FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS base
EXPOSE 8080
EXPOSE 8081

FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /source

# Internal/Versioned source code
COPY CustomCADs.slnx .
COPY Directory.Packages.props .
COPY Directory.Build.props .
COPY src/ src/
COPY tests/ tests/

# External/Dynamic source code
RUN dotnet run --project src/Tools/CodeGen -- codegen write
RUN dotnet restore

# Compile all source code
RUN dotnet build -c $BUILD_CONFIGURATION

FROM build AS publish
ARG BUILD_CONFIGURATION=Release

# Publish Entrypoint
RUN dotnet publish src/Presentation/Presentation.csproj -c $BUILD_CONFIGURATION -o /app/presentation /p:UseAppHost=false

# Publish Tools
RUN dotnet publish src/Tools/Migrations/Tools.Migrations.csproj -c $BUILD_CONFIGURATION -o /app/migrations
RUN dotnet publish src/Tools/Identity/Tools.Identity.csproj -c $BUILD_CONFIGURATION -o /app/identity

# Publish Scripts
COPY full-migration.sh .

FROM base AS final
WORKDIR /app

# Copy Migrations script & chmod it
COPY --from=publish /source/full-migration.sh .
RUN chmod +x full-migration.sh

# Copy all compiled application code
COPY --from=publish /app .

# Expose Entrypoint and set User
ENTRYPOINT ["dotnet", "presentation/Presentation.dll"]
USER app