global using CustomCADs.Modules.Printing.API.Customizations.Dtos;
global using CustomCADs.Modules.Printing.Application.Customizations.Dtos;
global using CustomCADs.Modules.Printing.Application.Materials.Dtos;
global using CustomCADs.Shared.API;
global using CustomCADs.Shared.Application.Abstractions.Requests.Sender;
global using CustomCADs.Shared.Domain;
global using CustomCADs.Shared.Domain.TypedIds.Printing;
global using FastEndpoints;
global using Microsoft.AspNetCore.Http;
