global using CustomCADs.Carts.Application.ActiveCarts.Dtos;
global using CustomCADs.Carts.Application.PurchasedCarts.Dtos;
global using CustomCADs.Carts.API.ActiveCarts.Dtos;
global using CustomCADs.Carts.API.PurchasedCarts.Dtos;
global using CustomCADs.Shared.Application.Abstractions.Requests.Sender;
global using CustomCADs.Shared.Domain;
global using CustomCADs.Shared.API;
global using FastEndpoints;
global using Microsoft.AspNetCore.Http;
