global using CustomCADs.Files.API.Cads.Dtos;
global using CustomCADs.Files.API.Images.Dtos;
global using CustomCADs.Shared.API;
global using CustomCADs.Shared.API.Extensions;
global using CustomCADs.Shared.Application.Abstractions.Requests.Sender;
global using CustomCADs.Shared.Domain;
global using CustomCADs.Shared.Domain.TypedIds.Files;
global using FastEndpoints;
global using Microsoft.AspNetCore.Http;
