name: Main Delivery pipeline

on:
  workflow_dispatch:
  push:
    branches: [main]
    tags-ignore: ["v*.*.*"]

jobs:
  ci:
    uses: ./.github/workflows/ci.yml

  deliver:
    needs: ci
    uses: ./.github/workflows/dockerhub-delivery.yml
    with:
      dockerfile: Dockerfile.production
      tag: git_version
    secrets:
      docker-password: ${{ secrets.DOCKER_PASSWORD }}
      docker-username: ${{ secrets.DOCKER_USERNAME }}
      docker-registry: ${{ secrets.DOCKER_REGISTRY }}
      docker-repository: ${{ secrets.DOCKER_REPOSITORY }}

  publish-sdk:
    needs: deliver
    uses: ./.github/workflows/sdk-publish.yml
    secrets:
      token: ${{ secrets.NPM_GAT }}
