name: Release Delivery pipeline

on:
  workflow_dispatch:
  push:
    branches: [release/*]
    tags-ignore: ["*"]

jobs:
  ci:
    uses: ./.github/workflows/ci.yml

  deliver:
    needs: ci
    uses: ./.github/workflows/dockerhub-delivery.yml
    with:
      dockerfile: Dockerfile.staging
      tag: staging
    secrets:
      docker-password: ${{ secrets.DOCKER_PASSWORD }}
      docker-username: ${{ secrets.DOCKER_USERNAME }}
      docker-registry: ${{ secrets.DOCKER_REGISTRY }}
      docker-repository: ${{ secrets.DOCKER_REPOSITORY }}
