name: Build & Test React SDK

on:
    workflow_call:

jobs:
    publish:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repo
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Set up Node
              uses: actions/setup-node@v4
              with:
                  node-version: "lts/*"
                  registry-url: "https://registry.npmjs.org/"

            - name: Install dependencies
              run: |
                  cd sdk/js/react
                  npm ci

            - name: Build SDK
              env:
                  VERSION: ${{ env.VERSION }}
              run: |
                  cd sdk/js/react
                  npm run build

            - name: Run Unit Tests
              run: |
                  cd sdk/js/react
                  npm run test
