// <auto-generated />
using System;
using System.Collections.Generic;
using CustomCADs.Modules.Delivery.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CustomCADs.Modules.Delivery.Persistence.Migrations
{
    [DbContext(typeof(DeliveryContext))]
    partial class DeliveryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Delivery")
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CustomCADs.Modules.Delivery.Domain.Shipments.Shipment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BuyerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("BuyerId");

                    b.Property<DateTimeOffset>("RequestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("RequestedAt");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.ComplexProperty<Dictionary<string, object>>("Address", "CustomCADs.Modules.Delivery.Domain.Shipments.Shipment.Address#ShipmentAddress", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("City");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Country");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Street");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Contact", "CustomCADs.Modules.Delivery.Domain.Shipments.Shipment.Contact#ShipmentContact", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Email")
                                .HasColumnType("text")
                                .HasColumnName("Email");

                            b1.Property<string>("Phone")
                                .HasColumnType("text")
                                .HasColumnName("Phone");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Info", "CustomCADs.Modules.Delivery.Domain.Shipments.Shipment.Info#ShipmentInfo", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("Count")
                                .HasColumnType("integer")
                                .HasColumnName("Count");

                            b1.Property<string>("Recipient")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Recipient");

                            b1.Property<double>("Weight")
                                .HasColumnType("double precision")
                                .HasColumnName("Weight");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Reference", "CustomCADs.Modules.Delivery.Domain.Shipments.Shipment.Reference#ShipmentReference", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Id")
                                .HasColumnType("text")
                                .HasColumnName("ReferenceId");

                            b1.Property<string>("Service")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Service");
                        });

                    b.HasKey("Id");

                    b.ToTable("Shipments", "Delivery");
                });
#pragma warning restore 612, 618
        }
    }
}
